name: run-selenium
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  Selenium-run:
    runs-on: ubuntu-latest
        
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v2
        with:
        # Optional: do not specify to match Chrome's version
          chromedriver-version: '108.0.5359.22'
        timeout-minutes: 10
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install libraries
        run: npm install 
        timeout-minutes: 10
        
      - name: Run Tests
        continue-on-error: true
        run:  npm test   
        
      - name: Generate report
        uses: actions/upload-artifact@v2
        with:
         name: Myreport.html
         path: "**/report"       
